### ISSUE TITLE
Can't get example working on windows 10 with -g vulkan

### ISSUE THREAD

**Issue by trsh** [Kode/Kore#465]
1) `git clone --recursive https://github.com/Kinc-Samples/Shader-Kinc.git`
2) `cd Shader-Kinc`
3) `git submodule foreach --recursive git pull origin master`
4) `node Kinc/make -g vulkan`

```
kincfile found.
Creating Windows project files.
(node:10228) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:112:11)
    at Object.join (path.js:375:7)
    at eval (eval at <anonymous> (C:\Projects\kha\forks\Shader-Kinc\Kinc\Tools\kincmake\out\Project.js:78:27), <anonymous>:96:35)
    at C:\Projects\kha\forks\Shader-Kinc\Kinc\Tools\kincmake\out\Project.js:78:251
    at new Promise (<anonymous>)
    at loadProject (C:\Projects\kha\forks\Shader-Kinc\Kinc\Tools\kincmake\out\Project.js:55:12)
    at Project.addProject (C:\Projects\kha\forks\Shader-Kinc\Kinc\Tools\kincmake\out\Project.js:436:37)
    at Function.create (C:\Projects\kha\forks\Shader-Kinc\Kinc\Tools\kincmake\out\Project.js:443:27)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async exportKoremakeProject (C:\Projects\kha\forks\Shader-Kinc\Kinc\Tools\kincmake\out\main.js:218:19)
(node:10228) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10228) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Error: korefile did not call resolve, no project created.
```

GPU GeForce GTX 750 Ti, latest NVIDIA drivers
Vulkan Instance Version: 1.1.126

**Works** when i do node `Kinc/make -g opengl`

**Comment by RobDangerous** [comment]
Can not reproduce that. https://github.com/Kode/Kinc/actions?query=workflow%3A%22Windows+%28Vulkan%29%22 also looks fine. Open kincmake in vscode and start it from there and look for that broken path.

**Comment by sh-dave** [comment]
might be a good idea to move the issue to kincmake and maybe print a warning when env `VULKAN_SDK` isn't set instead of just crashing?
